### ISSUE TITLE
[BUG] (multiple) Change api specs to use camelCase 

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#236] opened 2020-07-22 20:30 UTC
**Which repo (e.g., tx-logging)?**
pds, pdspi-guidance-example, pdspi-

**Expected Behavior**
All the API parameters should be using camelCase

**Actual Behavior**
we have some `_` here and there

**Information**

Please replace:
- settings_requested with settingsRequested 
- fhir_piid with fhirPiid
- mapper_piid with mapperPiid
- settings_used with settingsUsed
close this ticket when the above replacements have been made in the following repo's, dockerhub containers successfully build, Hong has been notified to deploy on stage-pds, and the updates test out ok.
- [ ] pds (pds/guidance, pds/patientVariables)
- [ ] guidance (pdspi-guidance-example/guidance)
- [ ] pds-cdm-specs (as needed)
- [ ] CDM
- [ ] other guidance plugins

**Comment by rajshruti18** [comment] 2020-07-22 20:39
Duplicate of #237

**Closed by rajshruti18** 2020-07-22 20:39 UTC
Labels: 2020-Oct-must, bug
